# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Phone')),
                ('email', models.EmailField(max_length=25, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Address')),
                ('text', models.TextField(max_length=1000, verbose_name='In use')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Application time')),
            ],
            options={
                'verbose_name': 'Звернення',
                'verbose_name_plural': 'Звернення',
            },
        ),
        migrations.AlterField(
            model_name='mycontactmodel',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Phone'),
        ),
    ]
