# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20170617_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectmodel',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='connectmodel',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='connectmodel',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='connectmodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time'),
        ),
    ]
