# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MethodInUseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='Text')),
                ('use', models.BooleanField(default=False, verbose_name='In use')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='method.MethodInUseModel')),
            ],
            options={
                'verbose_name': 'Використовується',
                'verbose_name_plural': 'Використовується',
            },
        ),
    ]
