# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostCommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30, verbose_name='User name hwo post comment')),
                ('userEmail', models.EmailField(max_length=30, verbose_name='User email hwo post comment')),
                ('body', models.TextField(max_length=1000, verbose_name='Comment text')),
                ('likes', models.IntegerField(default=0, verbose_name='Comment likes')),
                ('views', models.IntegerField(default=0, verbose_name='Comment views')),
                ('createTime', models.FloatField(default=1497623340.918113, verbose_name='Comment create time')),
            ],
            options={
                'verbose_name': 'PostComment',
                'verbose_name_plural': 'PostComments',
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Post title')),
                ('body', models.TextField(max_length=5000, verbose_name='Post Text')),
                ('likes', models.IntegerField(default=0, verbose_name='Post likes')),
                ('views', models.IntegerField(default=0, verbose_name='Post views')),
                ('createTime', models.FloatField(default=1497623340.9172075, verbose_name='Post create time')),
                ('image', models.ImageField(upload_to='images', verbose_name='Post image')),
                ('lastMessTime', models.FloatField(default=1497623340.9172697, verbose_name='Last messege time')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.AddField(
            model_name='postcommentmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.PostModel'),
        ),
    ]
