# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcommentmodel',
            name='createTime',
            field=models.FloatField(default=1497623356.988723, verbose_name='Comment create time'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='createTime',
            field=models.FloatField(default=1497623356.9878757, verbose_name='Post create time'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='lastMessTime',
            field=models.FloatField(default=1497623356.9879315, verbose_name='Last messege time'),
        ),
    ]
