# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20170616_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='lastMessTime',
        ),
        migrations.AlterField(
            model_name='postcommentmodel',
            name='createTime',
            field=models.FloatField(verbose_name='Comment create time'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='createTime',
            field=models.FloatField(verbose_name='Post create time'),
        ),
    ]
