# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20170618_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcommentmodel',
            name='createTime',
            field=models.DateTimeField(blank=True, verbose_name='Comment create time'),
        ),
    ]
