# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20170618_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='createTime',
            field=models.DateTimeField(blank=True, verbose_name='Post create time'),
        ),
    ]
