# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20170618_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcommentmodel',
            old_name='userEmail',
            new_name='Email',
        ),
    ]
