# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=25, verbose_name='First Name')),
                ('bookName', models.CharField(max_length=50, verbose_name='Last Name')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Application time')),
            ],
            options={
                'verbose_name': 'My Book',
                'verbose_name_plural': 'My Books',
            },
        ),
    ]
