# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_booksmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('response', models.CharField(max_length=10000, verbose_name='Response text')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Response time')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('dislikes', models.IntegerField(default=0, verbose_name='Dislikes')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('parentResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.ResponseModel', verbose_name='Dislikes')),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
            },
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='author',
            field=models.CharField(max_length=25, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='bookName',
            field=models.CharField(max_length=50, verbose_name='Book Name'),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time'),
        ),
    ]
