# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20170422_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=50, verbose_name='Last Name')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Application time')),
                ('areaCode', models.IntegerField(verbose_name='Area code')),
                ('telNum', models.IntegerField(verbose_name='Phone')),
                ('emailId', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Application for Project',
                'verbose_name_plural': 'Applications for Project',
            },
        ),
        migrations.DeleteModel(
            name='ApplicationProject',
        ),
    ]
