# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20170617_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(max_length=200, verbose_name='Slogan')),
                ('use', models.BooleanField(default=False, verbose_name='In use')),
                ('text', models.TextField(max_length=3000, verbose_name='Text')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
            ],
            options={
                'verbose_name': 'About Me',
                'verbose_name_plural': 'About Me',
            },
        ),
        migrations.RemoveField(
            model_name='responsemodel',
            name='parentResponse',
        ),
        migrations.DeleteModel(
            name='ResponseModel',
        ),
    ]
