# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20170617_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='IUseCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category name')),
                ('use', models.BooleanField(default=False, verbose_name='In use')),
            ],
            options={
                'verbose_name_plural': 'I Use Categories',
                'verbose_name': 'I Use Category',
            },
        ),
        migrations.CreateModel(
            name='IUseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category name')),
                ('descr', models.CharField(max_length=200, verbose_name='Description')),
                ('link', models.URLField(verbose_name='Link')),
                ('use', models.BooleanField(default=False, verbose_name='In use')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.IUseCategoryModel')),
            ],
            options={
                'verbose_name_plural': 'I Use',
                'verbose_name': 'I Use',
            },
        ),
    ]
