# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_auto_20170617_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекти'},
        ),
    ]
