# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_auto_20170617_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iusemodel',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
    ]
