# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Advice name')),
                ('use', models.BooleanField(default=False, verbose_name='In use')),
            ],
            options={
                'verbose_name_plural': 'Категорії консультування',
                'verbose_name': 'Катерія консультування',
            },
        ),
        migrations.CreateModel(
            name='AdviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Description')),
                ('use', models.BooleanField(default=False, verbose_name='In use')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.AdviceCategoryModel')),
            ],
            options={
                'verbose_name_plural': 'Консультації',
                'verbose_name': 'Консультація',
            },
        ),
    ]
