# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Course name')),
                ('descr', models.CharField(max_length=300, verbose_name='Description name')),
                ('descrBelow', models.CharField(max_length=300, verbose_name='Description below name')),
                ('link', models.URLField(default=None, verbose_name='Download link')),
                ('use', models.BooleanField(default=False, verbose_name='In use')),
            ],
            options={
                'verbose_name_plural': 'Курси',
                'verbose_name': 'Курс',
            },
        ),
        migrations.CreateModel(
            name='OnCourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Text')),
                ('use', models.BooleanField(default=False, verbose_name='In use')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.CourseModel')),
            ],
            options={
                'verbose_name_plural': 'На курсі',
                'verbose_name': 'На курсі',
            },
        ),
        migrations.AlterField(
            model_name='advicecategorymodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Advice category name'),
        ),
        migrations.AlterField(
            model_name='advicemodel',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Text'),
        ),
    ]
