# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170617_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='descr',
            field=models.TextField(max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='descrBelow',
            field=models.TextField(max_length=300, verbose_name='Description below'),
        ),
    ]
